name: Ubuntu Linux (x86_64)

on:
  push:
    branches:
      - "*"
    tags:
      - "*.*.*"

  pull_request:
    branches:
      - "*"

jobs:
  build-test-release:
    name: Build, Test, and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install Dependencies
        run: |
          bun install

      - name: Build
        id: build
        run: |
          bun run build

      - name: Run Tests
        id: test
        if: success()
        run: bun test

      - name: Prepare package
        id: package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && success()
        run: |
          cd dist && tar -czvf bli-${{ github.ref_name }}-linux.tar.gz *
        env:
          tag: ${{ github.ref_name }}

      - name: Upload Release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && success()
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/bli-${{ github.ref_name }}-linux.tar.gz
